# theme: jekyll-theme-hacker
title: Testing 
description: Testing Jekyll and Jquery tables 
# plugins:
#   - jekyll-relative-links
# relative_links:
#   enabled: true
#   collections: true
markdown: kramdown
# permalink: /blog/:year/:month/:day/:title
